name: Tests
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  front:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Run front tests
        run: npm ci
      - run: npx nx run-many --target=serve --projects=poke-front,poke-bff && npx nx cypress poke-front-e2e
        continue-on-error: false
  
  bff:
    name: Bff Test
    runs-on: ubuntu-latest
    needs: front
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Run bff tests
        run: npm ci
      - run: npx nx test poke-bff
        continue-on-error: false
          