name: Tests
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  bff:
    name: Bff Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Run bff tests
        run: npm ci
      - run: npx nx test poke-bff
        continue-on-error: false

  front:
    name: Cypress Test
    runs-on: ubuntu-latest
    # needs: bff
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          project: ./packages/poke-front
          browser: chrome
          start: npx nx serve poke-front
          wait-on: 'http://localhost:3000'
          command: npx nx cypress poke-front
          headed: true
        continue-on-error: false
